# Project Milestone 5

In [546]:
# Importing Pandas packages required for this excercise.

import sqlite3
import pandas as pd
import seaborn as sns
import matplotlib

import urllib.request, urllib.parse, urllib.error
import requests
from bs4 import BeautifulSoup
import ssl
import re

import matplotlib.dates as mdates
from matplotlib.dates import DateFormatter
import matplotlib.ticker as tick

In [548]:
conn = sqlite3.connect("DSC540FinalProjectDB",timeout=10)

cursor = conn.cursor()

In [550]:
try:
    with sqlite3.connect("DSC540FinalProjectDB.db") as conn:
        cursor = conn.cursor()
        conn.commit()
        print("Succeeded")
except sqlite3.OperationalError as e:
    print("Failed to open database:", e)

Succeeded

In [552]:
# loading covid CSV file for data transformation and cleaning

covid = pd.read_csv("./time_series_covid_19_confirmed.csv")
covid = covid.rename(columns={'Country/Region': 'Country'})

covid.head()

,Province/State,Country,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,299,349,367,423,444,484,521,555,607,665
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,333,361,377,383,400,409,416,433,446,467
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,1251,1320,1423,1468,1572,1666,1761,1825,1914,1983
3,NaN,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,466,501,525,545,564,583,601,601,638,646
4,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,10,14,16,17,19,19,19,19,19,19

In [554]:
# Selecting 4 countries that has highest number of cases

covidMelt = covid.melt(id_vars = ['Country'])
coviddropNan = covidMelt.dropna()
coviddropvariable = coviddropNan[coviddropNan['variable'] != 'Province/State']
covidCountries = coviddropvariable.groupby(['Country'])['value'].sum().reset_index().sort_values(by = 'value',ascending = False)
covidCountries = covidCountries.rename(columns={'value': 'Covidcases'})
covidCountries[0:5]

     Country    Covidcases
171       US  6278184.3773
36     China  5267388.7564
84     Italy     2977275.0
156    Spain     2574218.0
65   Germany     1986377.0

In [556]:
# Write the covid countries DataFrame to a SQLite table
covidCountries.to_sql("covidCountries", conn, if_exists="replace")

185

In [558]:
# reading covidtopCountries table data in sqlite database
res = conn.execute("SELECT * FROM covidCountries")
for row in res:
    print(row)

(171, 'US', 6278184.3773)
(36, 'China', 5267388.7564)
(84, 'Italy', 2977275.0)
(156, 'Spain', 2574218.0)
(65, 'Germany', 1986377.0)
(61, 'France', 1748435.0816000002)
(80, 'Iran', 1329967.0)
(175, 'United Kingdom', 923997.1052)
(170, 'Turkey', 526623.2069999999)
(161, 'Switzerland', 445000.0457)
(90, 'Korea, South', 390965.0)
(16, 'Belgium', 379608.8333)
(120, 'Netherlands', 362341.0139)
(32, 'Canada', 283292.1318)
(9, 'Austria', 248548.0663)
(23, 'Brazil', 228935.8397)
(135, 'Portugal', 212170.1754)
(83, 'Israel', 150816.0)
(160, 'Sweden', 147645.0)
(126, 'Norway', 128255.9409)
(138, 'Russia', 125270.0)
(8, 'Australia', 112560.8928)
(82, 'Ireland', 105561.4503)
(46, 'Denmark', 99170.84909999999)
(45, 'Czechia', 90898.2905)
(86, 'Japan', 86311.0)
(35, 'Chile', 85974.7819)
(78, 'India', 82647.0)
(105, 'Malaysia', 79299.0)
(51, 'Ecuador', 79100.9854)
(134, 'Poland', 78867.06450000001)
(137, 'Romania', 73497.91)
(128, 'Pakistan', 65871.72039999999)
(132, 'Peru', 61137.7948)
(133, 'Philippines', 59545.0)
(101, 'Luxembourg', 55244.9449)
(145, 'Saudi Arabia', 51259.0)
(79, 'Indonesia', 49532.132)
(165, 'Thailand', 43873.0)
(60, 'Finland', 43185.0)
(47, 'Diamond Princess', 41300.0)
(111, 'Mexico', 41241.081699999995)
(174, 'United Arab Emirates', 38103.0)
(147, 'Serbia', 37518.0224)
(67, 'Greece', 37226.898499999996)
(136, 'Qatar', 36082.538700000005)
(129, 'Panama', 35916.755900000004)
(150, 'Singapore', 35136.1166)
(154, 'South Africa', 33442.378)
(50, 'Dominican Republic', 33230.573000000004)
(77, 'Iceland', 31339.9423)
(37, 'Colombia', 30892.2736)
(6, 'Argentina', 27772.9672)
(52, 'Egypt', 26103.0)
(173, 'Ukraine', 25373.545)
(2, 'Algeria', 24044.6935)
(42, 'Croatia', 23376.3)
(152, 'Slovenia', 22376.1467)
(56, 'Estonia', 22022.6089)
(81, 'Iraq', 20519.0)
(116, 'Morocco', 19245.699099999998)
(12, 'Bahrain', 19019.5775)
(121, 'New Zealand', 18123.985399999998)
(15, 'Belarus', 17185.6632)
(112, 'Moldova', 16394.7815)
(76, 'Hungary', 15526.665799999999)
(7, 'Armenia', 15190.1073)
(100, 'Lithuania', 14942.0507)
(92, 'Kuwait', 14367.25)
(21, 'Bosnia and Herzegovina', 12729.595000000001)
(96, 'Lebanon', 12526.717)
(10, 'Azerbaijan', 11723.720000000001)
(151, 'Slovakia', 11192.368)
(25, 'Bulgaria', 11035.2197)
(88, 'Kazakhstan', 11030.943299999999)
(95, 'Latvia', 10601.4828)
(125, 'North Macedonia', 10344.3539)
(169, 'Tunisia', 10298.0)
(3, 'Andorra', 9758.0281)
(163, 'Taiwan*', 9479.7)
(31, 'Cameroon', 9391.3501)
(40, 'Costa Rica', 9321.9955)
(44, 'Cyprus', 8656.5563)
(176, 'Uruguay', 8135.7114)
(177, 'Uzbekistan', 7746.9628)
(143, 'San Marino', 7340.4002)
(1, 'Albania', 7158.3216)
(87, 'Jordan', 7008.75)
(127, 'Oman', 7002.0)
(26, 'Burkina Faso', 6972.6767)
(0, 'Afghanistan', 6828.0)
(43, 'Cuba', 6581.0)
(179, 'Vietnam', 6265.0)
(41, "Cote d'Ivoire", 5837.9929)
(108, 'Malta', 5435.3129)
(66, 'Ghana', 5285.9233)
(75, 'Honduras', 4716.9581)
(146, 'Senegal', 4548.045)
(180, 'West Bank and Gaza', 4539.1854)
(124, 'Nigeria', 4221.7573)
(110, 'Mauritius', 4201.3)
(13, 'Bangladesh', 4154.0413)
(123, 'Niger', 4034.6895)
(157, 'Sri Lanka', 3948.0)
(64, 'Georgia', 3905.6723)
(93, 'Kyrgyzstan', 3777.9705)
(115, 'Montenegro', 3657.8)
(24, 'Brunei', 3559.263)
(178, 'Venezuela', 3375.8341)
(20, 'Bolivia', 3292.1211000000003)
(91, 'Kosovo', 3049.5056130000003)
(39, 'Congo (Kinshasa)', 2952.7204)
(30, 'Cambodia', 2884.4667)
(89, 'Kenya', 2466.8826)
(70, 'Guinea', 2152.249)
(168, 'Trinidad and Tobago', 2070.4692999999997)
(139, 'Rwanda', 1988.9336)
(131, 'Paraguay', 1916.1136999999999)
(99, 'Liechtenstein', 1749.69)
(48, 'Djibouti', 1709.4153999999999)
(113, 'Monaco', 1492.15)
(69, 'Guatemala', 1419.5527)
(103, 'Madagascar', 1390.1022)
(53, 'El Salvador', 1157.8977)
(85, 'Jamaica', 1088.8121)
(167, 'Togo', 1058.4443)
(14, 'Barbados', 977.6507)
(107, 'Mali', 949.574526)
(58, 'Ethiopia', 912.6347000000001)
(172, 'Uganda', 905.0)
(183, 'Zambia', 722.8666000000001)
(38, 'Congo (Brazzaville)', 679.7203999999999)
(106, 'Maldives', 614.4235)
(164, 'Tanzania', 536.5198)
(27, 'Burma', 526.8722)
(62, 'Gabon', 526.8057)
(72, 'Guyana', 505.25)
(55, 'Eritrea', 500.9617)
(114, 'Mongolia', 497.7092)
(11, 'Bahamas', 495.63800000000003)
(18, 'Benin', 403.62350000000004)
(73, 'Haiti', 376.686)
(59, 'Fiji', 373.35159999999996)
(162, 'Syria', 372.79889000000003)
(54, 'Equatorial Guinea', 365.5)
(97, 'Liberia', 363.9986)
(71, 'Guinea-Bissau', 361.6233)
(94, 'Laos', 352.351766)
(98, 'Libya', 327.56343100000004)
(119, 'Nepal', 319.4167)
(148, 'Seychelles', 299.8124)
(118, 'Namibia', 292.5328)
(158, 'Sudan', 282.0804)
(153, 'Somalia', 277.3517)
(117, 'Mozambique', 258.863867)
(4, 'Angola', 249.6712)
(5, 'Antigua and Barbuda', 233.2644)
(19, 'Bhutan', 227.9478)
(57, 'Eswatini', 221.9434)
(49, 'Dominica', 221.04399999999998)
(34, 'Chad', 213.1864)
(74, 'Holy See', 208.3563)
(184, 'Zimbabwe', 208.0)
(141, 'Saint Lucia', 201.9305)
(130, 'Papua New Guinea', 170.6405)
(159, 'Suriname', 165.8915)
(33, 'Central African Republic', 165.5505)
(68, 'Grenada', 161.4375)
(109, 'Mauritania', 160.9487)
(166, 'Timor-Leste', 145.853322)
(29, 'Cabo Verde', 135.497)
(102, 'MS Zaandam', 125.0)
(140, 'Saint Kitts and Nevis', 115.574824)
(22, 'Botswana', 114.35640000000001)
(104, 'Malawi', 114.047217)
(63, 'Gambia', 100.1331)
(17, 'Belize', 76.6507)
(149, 'Sierra Leone', 75.680666)
(142, 'Saint Vincent and the Grenadines', 72.6971)
(28, 'Burundi', 72.5458)
(182, 'Yemen', 68.069115)
(155, 'South Sudan', 63.184)
(181, 'Western Sahara', 51.3297)
(122, 'Nicaragua', 44.658199999999994)
(144, 'Sao Tome and Principe', 38.799441)

In [560]:
# loading covid CSV file for data transformation and cleaning

url = 'https://en.wikipedia.org/wiki/COVID-19_pandemic_by_country_and_territory'

In [562]:
dfs = pd.read_html(url)

In [563]:
corona_df=dfs[12]
corona_df_col=corona_df.drop(columns=['Unnamed: 0'])

In [564]:
# remove records where deaths are equals to 0 or less
corona_df_clean=corona_df_col[(corona_df_col['Deaths'])>"0"]

In [565]:
# Write the covid DataFrame to a SQLite table
corona_df_clean.to_sql("coronawebdata", conn, if_exists="replace")

232

In [570]:
def read_json_from_web_api(url):
    """
    Reads a JSON file from a web API.

    Args:
        url (str): The URL of the web API endpoint.

    Returns:
        dict: The JSON data as a Python dictionary, or None if an error occurs.
    """
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Request error: {e}")
        return None
    except json.JSONDecodeError as e:
        print(f"JSON decode error: {e}")
        return None

In [572]:
# call Covid 19 API and load it in Json Format
url = "https://api.covidtracking.com/v1/us/daily.json"  # Replace with the actual API endpoint
data = read_json_from_web_api(url)
df = pd.json_normalize(data)
df = df.drop('hash',axis=1)    
df.head(10)

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,totalTestResults,lastModified,recovered,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20210307,56,28756489.0,74582825.0,11808.0,40199.0,776361.0,8134.0,45475.0,2802.0,...,363825123,2021-03-07T24:00:00Z,None,0,0,842,726,131835,41835,1170059
1,20210306,56,28714654.0,74450990.0,11783.0,41401.0,775635.0,8409.0,45453.0,2811.0,...,362655064,2021-03-06T24:00:00Z,None,0,0,1680,503,143835,60015,1430992
2,20210305,56,28654639.0,74307155.0,12213.0,42541.0,775132.0,8634.0,45373.0,2889.0,...,361224072,2021-03-05T24:00:00Z,None,0,0,2221,2781,271917,68787,1744417
3,20210304,56,28585852.0,74035238.0,12405.0,44172.0,772351.0,8970.0,45293.0,2973.0,...,359479655,2021-03-04T24:00:00Z,None,0,0,1743,1530,177957,65487,1590984
4,20210303,56,28520365.0,73857281.0,11778.0,45462.0,770821.0,9359.0,45214.0,3094.0,...,357888671,2021-03-03T24:00:00Z,None,0,0,2449,2172,267001,66836,1406795
5,20210302,56,28453529.0,73590280.0,11196.0,46388.0,768649.0,9465.0,45084.0,3169.0,...,356481876,2021-03-02T24:00:00Z,None,0,0,1728,1871,255779,54248,1343519
6,20210301,56,28399281.0,73334501.0,11748.0,46738.0,766778.0,9595.0,44956.0,3171.0,...,355138357,2021-03-01T24:00:00Z,None,0,0,1241,1024,118077,48092,1154440
7,20210228,56,28351189.0,73216424.0,11708.0,47352.0,765754.0,9802.0,44907.0,3245.0,...,353983917,2021-02-28T24:00:00Z,None,0,0,1051,879,203599,54349,1408422
8,20210227,56,28296840.0,73012825.0,11731.0,48871.0,764875.0,10114.0,44875.0,3335.0,...,352575495,2021-02-27T24:00:00Z,None,0,0,1847,1428,205090,71245,1655179
9,20210226,56,28225595.0,72807735.0,11945.0,51112.0,763447.0,10466.0,44791.0,3466.0,...,350920316,2021-02-26T24:00:00Z,None,0,0,2141,1868,276829,74857,1803309

In [573]:
df_clean = df.dropna(subset=['positive', 'negative','pending','hospitalizedCurrently','hospitalizedCumulative','inIcuCurrently','inIcuCumulative','onVentilatorCurrently'])
print(df_clean)

         date  states    positive    negative  pending  hospitalizedCurrently  \
0    20210307      56  28756489.0  74582825.0  11808.0                40199.0
1    20210306      56  28714654.0  74450990.0  11783.0                41401.0
2    20210305      56  28654639.0  74307155.0  12213.0                42541.0
3    20210304      56  28585852.0  74035238.0  12405.0                44172.0
4    20210303      56  28520365.0  73857281.0  11778.0                45462.0
..        ...     ...         ...         ...      ...                    ...
342  20200330      56    171965.0    416268.0  65369.0                15892.0
343  20200329      56    150826.0    366103.0  65404.0                14055.0
344  20200328      56    131143.0    324271.0  65698.0                12393.0
345  20200327      56    111358.0    255808.0  59795.0                10887.0
346  20200326      56     92143.0    210652.0  60131.0                 7805.0

     hospitalizedCumulative  inIcuCurrently  inIcuCumulative  \
0                  776361.0          8134.0          45475.0
1                  775635.0          8409.0          45453.0
2                  775132.0          8634.0          45373.0
3                  772351.0          8970.0          45293.0
4                  770821.0          9359.0          45214.0
..                      ...             ...              ...
342                  5208.0          3087.0            187.0
343                  4624.0          2456.0            156.0
344                  4065.0          2174.0            140.0
345                  3383.0          1792.0            124.0
346                  2606.0          1299.0             91.0

     onVentilatorCurrently  ...  totalTestResults          lastModified  \
0                   2802.0  ...         363825123  2021-03-07T24:00:00Z
1                   2811.0  ...         362655064  2021-03-06T24:00:00Z
2                   2889.0  ...         361224072  2021-03-05T24:00:00Z
3                   2973.0  ...         359479655  2021-03-04T24:00:00Z
4                   3094.0  ...         357888671  2021-03-03T24:00:00Z
..                     ...  ...               ...                   ...
342                  449.0  ...           1068981  2020-03-30T24:00:00Z
343                  433.0  ...            968389  2020-03-29T24:00:00Z
344                  390.0  ...            881415  2020-03-28T24:00:00Z
345                  293.0  ...            769985  2020-03-27T24:00:00Z
346                  258.0  ...            668725  2020-03-26T24:00:00Z

     recovered  total  posNeg deathIncrease hospitalizedIncrease  \
0         None      0       0           842                  726
1         None      0       0          1680                  503
2         None      0       0          2221                 2781
3         None      0       0          1743                 1530
4         None      0       0          2449                 2172
..         ...    ...     ...           ...                  ...
342       None      0       0           584                  584
343       None      0       0           506                  559
344       None      0       0           550                  682
345       None      0       0           411                  777
346       None      0       0           313                  655

     negativeIncrease  positiveIncrease  totalTestResultsIncrease
0              131835             41835                   1170059
1              143835             60015                   1430992
2              271917             68787                   1744417
3              177957             65487                   1590984
4              267001             66836                   1406795
..                ...               ...                       ...
342             50165             21139                    100592
343             41832             19683                     86974
344             68463             19785                    111430
345             45156             19215                    101260
346             42359             17592                    106945

[347 rows x 24 columns]

In [576]:
# Write the covid web DataFrame to a SQLite table
corona_df_clean.to_sql("cleaneddfweb", conn, if_exists="replace")

232

In [578]:
# pushing Covid API Dataframe into Sql Table
df_clean.to_sql("cleanedAPI", conn, if_exists="replace")

347

## Join covidcountries and Cleaneddfweb tables to get death values by countries

In [580]:
sql = '''
            SELECT cc.Country,cc.Covidcases,cf.Deaths
            FROM covidCountries AS cc 
                INNER JOIN cleaneddfweb AS cf ON cf.Country = cc.Country
            ORDER BY cc.Country
            
        '''

cursor.execute(sql)

# Fetching rows from the result table
result = cursor.fetchall()
for row in result:
    print(row)

('Afghanistan', 6828.0, '7998')
('Albania', 7158.3216, '3605')
('Algeria', 24044.6935, '6881')
('Andorra', 9758.0281, '159')
('Angola', 249.6712, '1937')
('Antigua and Barbuda', 233.2644, '146')
('Argentina', 27772.9672, '130663')
('Armenia', 15190.1073, '8777')
('Australia', 112560.8928, '25236')
('Austria', 248548.0663, '22534')
('Azerbaijan', 11723.720000000001, '10353')
('Bahamas', 495.63800000000003, '849')
('Bahrain', 19019.5775, '1536')
('Bangladesh', 4154.0413, '29499')
('Barbados', 977.6507, '593')
('Belarus', 17185.6632, '7118')
('Belgium', 379608.8333, '34339')
('Belize', 76.6507, '688')
('Benin', 403.62350000000004, '163')
('Bhutan', 227.9478, '21')
('Bolivia', 3292.1211000000003, '22387')
('Bosnia and Herzegovina', 12729.595000000001, '16392')
('Botswana', 114.35640000000001, '2801')
('Brazil', 228935.8397, '702116')
('Brunei', 3559.263, '179')
('Bulgaria', 11035.2197, '38700')
('Burkina Faso', 6972.6767, '400')
('Burundi', 72.5458, '15')
('Cabo Verde', 135.497, '417')
('Cambodia', 2884.4667, '3056')
('Cameroon', 9391.3501, '1974')
('Canada', 283292.1318, '55282')
('Central African Republic', 165.5505, '113')
('Chad', 213.1864, '194')
('Chile', 85974.7819, '62730')
('Colombia', 30892.2736, '142727')
('Costa Rica', 9321.9955, '9372')
('Croatia', 23376.3, '18752')
('Cuba', 6581.0, '8530')
('Cyprus', 8656.5563, '1451')
('Denmark', 99170.84909999999, '9693')
('Djibouti', 1709.4153999999999, '189')
('Dominica', 221.04399999999998, '74')
('Dominican Republic', 33230.573000000004, '4384')
('Ecuador', 79100.9854, '36050')
('Egypt', 26103.0, '24830')
('El Salvador', 1157.8977, '4230')
('Equatorial Guinea', 365.5, '183')
('Eritrea', 500.9617, '103')
('Estonia', 22022.6089, '2998')
('Eswatini', 221.9434, '1427')
('Ethiopia', 912.6347000000001, '7574')
('Fiji', 373.35159999999996, '885')
('Finland', 43185.0, '11466')
('France', 1748435.0816000002, '168091')
('Gabon', 526.8057, '307')
('Gambia', 100.1331, '372')
('Georgia', 3905.6723, '17150')
('Germany', 1986377.0, '174979')
('Ghana', 5285.9233, '1462')
('Greece', 37226.898499999996, '39258')
('Grenada', 161.4375, '238')
('Guatemala', 1419.5527, '20203')
('Guinea', 2152.249, '468')
('Guinea-Bissau', 361.6233, '177')
('Guyana', 505.25, '1302')
('Haiti', 376.686, '860')
('Honduras', 4716.9581, '11114')
('Hungary', 15526.665799999999, '49053')
('Iceland', 31339.9423, '186')
('India', 82647.0, '533623')
('Indonesia', 49532.132, '162059')
('Iran', 1329967.0, '146837')
('Iraq', 20519.0, '25375')
('Israel', 150816.0, '12707')
('Italy', 2977275.0, '197307')
('Jamaica', 1088.8121, '3611')
('Japan', 86311.0, '74694')
('Jordan', 7008.75, '14122')
('Kazakhstan', 11030.943299999999, '19072')
('Kenya', 2466.8826, '5689')
('Kosovo', 3049.5056130000003, '3212')
('Kuwait', 14367.25, '2570')
('Kyrgyzstan', 3777.9705, '1024')
('Laos', 352.351766, '671')
('Latvia', 10601.4828, '7475')
('Lebanon', 12526.717, '10947')
('Liberia', 363.9986, '294')
('Libya', 327.56343100000004, '6437')
('Liechtenstein', 1749.69, '89')
('Lithuania', 14942.0507, '9810')
('Luxembourg', 55244.9449, '1000')
('Madagascar', 1390.1022, '1428')
('Malawi', 114.047217, '2686')
('Malaysia', 79299.0, '37351')
('Maldives', 614.4235, '316')
('Mali', 949.574526, '743')
('Malta', 5435.3129, '922')
('Mauritania', 160.9487, '997')
('Mauritius', 4201.3, '1073')
('Mexico', 41241.081699999995, '334551')
('Moldova', 16394.7815, '12245')
('Monaco', 1492.15, '67')
('Mongolia', 497.7092, '2136')
('Montenegro', 3657.8, '2654')
('Morocco', 19245.699099999998, '16305')
('Mozambique', 258.863867, '2252')
('Namibia', 292.5328, '4108')
('Nepal', 319.4167, '12031')
('Netherlands', 362341.0139, '22986')
('New Zealand', 18123.985399999998, '4284')
('Nicaragua', 44.658199999999994, '245')
('Niger', 4034.6895, '315')
('Nigeria', 4221.7573, '3155')
('North Macedonia', 10344.3539, '9978')
('Norway', 128255.9409, '5732')
('Oman', 7002.0, '4628')
('Pakistan', 65871.72039999999, '30656')
('Panama', 35916.755900000004, '8748')
('Papua New Guinea', 170.6405, '670')
('Paraguay', 1916.1136999999999, '19880')
('Peru', 61137.7948, '220975')
('Philippines', 59545.0, '66864')
('Poland', 78867.06450000001, '120726')
('Portugal', 212170.1754, '28809')
('Qatar', 36082.538700000005, '690')
('Romania', 73497.91, '68825')
('Russia', 125270.0, '403188')
('Rwanda', 1988.9336, '1468')
('Saint Kitts and Nevis', 115.574824, '46')
('Saint Lucia', 201.9305, '410')
('Saint Vincent and the Grenadines', 72.6971, '124')
('San Marino', 7340.4002, '126')
('Sao Tome and Principe', 38.799441, '80')
('Saudi Arabia', 51259.0, '9646')
('Senegal', 4548.045, '1971')
('Serbia', 37518.0224, '18057')
('Seychelles', 299.8124, '172')
('Sierra Leone', 75.680666, '125')
('Singapore', 35136.1166, '2024')
('Slovakia', 11192.368, '21227')
('Slovenia', 22376.1467, '10083')
('Somalia', 277.3517, '1361')
('South Africa', 33442.378, '102595')
('South Sudan', 63.184, '147')
('Spain', 2574218.0, '121852')
('Sri Lanka', 3948.0, '16907')
('Sudan', 282.0804, '5046')
('Suriname', 165.8915, '1406')
('Sweden', 147645.0, '27399')
('Switzerland', 445000.0457, '14170')
('Syria', 372.79889000000003, '3163')
('Tanzania', 536.5198, '846')
('Thailand', 43873.0, '34715')
('Timor-Leste', 145.853322, '138')
('Togo', 1058.4443, '290')
('Trinidad and Tobago', 2070.4692999999997, '4390')
('Tunisia', 10298.0, '29423')
('Turkey', 526623.2069999999, '101419')
('Uganda', 905.0, '3632')
('Ukraine', 25373.545, '109920')
('United Arab Emirates', 38103.0, '2349')
('United Kingdom', 923997.1052, '232112')
('Uruguay', 8135.7114, '7682')
('Uzbekistan', 7746.9628, '1016')
('Venezuela', 3375.8341, '5856')
('Vietnam', 6265.0, '43206')
('Yemen', 68.069115, '2159')
('Zambia', 722.8666000000001, '4077')
('Zimbabwe', 208.0, '5740')

## Get Year = 2021 data for covid i.e. positive, negative and pending reports for covid patient.

In [585]:
sql = '''
            SELECT substr(date,1,4) as APIDate,positive,negative,pending,hospitalizedCurrently
            FROM cleanedAPI AS cf 
            WHERE substr(date,1,4) = '2021'
                        
        '''

cursor.execute(sql)

# Fetching rows from the result table
result = cursor.fetchall()
for row in result:
    print(row)

('2021', 28756489.0, 74582825.0, 11808.0, 40199.0)
('2021', 28714654.0, 74450990.0, 11783.0, 41401.0)
('2021', 28654639.0, 74307155.0, 12213.0, 42541.0)
('2021', 28585852.0, 74035238.0, 12405.0, 44172.0)
('2021', 28520365.0, 73857281.0, 11778.0, 45462.0)
('2021', 28453529.0, 73590280.0, 11196.0, 46388.0)
('2021', 28399281.0, 73334501.0, 11748.0, 46738.0)
('2021', 28351189.0, 73216424.0, 11708.0, 47352.0)
('2021', 28296840.0, 73012825.0, 11731.0, 48871.0)
('2021', 28225595.0, 72807735.0, 11945.0, 51112.0)
('2021', 28150738.0, 72530906.0, 11813.0, 52669.0)
('2021', 28075173.0, 72258697.0, 12548.0, 54118.0)
('2021', 28001915.0, 72013379.0, 11200.0, 55058.0)
('2021', 27932810.0, 71788112.0, 9499.0, 55403.0)
('2021', 27880280.0, 71664501.0, 9442.0, 56159.0)
('2021', 27821578.0, 71507723.0, 9408.0, 58222.0)
('2021', 27749224.0, 71365933.0, 8711.0, 59882.0)
('2021', 27674548.0, 71141178.0, 8679.0, 62224.0)
('2021', 27607724.0, 70922687.0, 8548.0, 63329.0)
('2021', 27540885.0, 70689021.0, 11547.0, 64457.0)
('2021', 27484573.0, 70587919.0, 11494.0, 65379.0)
('2021', 27429496.0, 70444531.0, 11515.0, 66947.0)
('2021', 27357332.0, 70272654.0, 11529.0, 69207.0)
('2021', 27266690.0, 70038361.0, 9434.0, 71471.0)
('2021', 27165660.0, 69782378.0, 11981.0, 74208.0)
('2021', 27063243.0, 69522254.0, 12079.0, 76979.0)
('2021', 26968049.0, 69366393.0, 10516.0, 79179.0)
('2021', 26875063.0, 69029225.0, 12114.0, 80055.0)
('2021', 26797326.0, 68887069.0, 12061.0, 81439.0)
('2021', 26701332.0, 68678766.0, 12070.0, 84233.0)
('2021', 26586775.0, 68396289.0, 11546.0, 86373.0)
('2021', 26455629.0, 68125535.0, 11914.0, 88668.0)
('2021', 26331722.0, 67908039.0, 12077.0, 91440.0)
('2021', 26214762.0, 67683540.0, 10590.0, 92880.0)
('2021', 26097146.0, 67516458.0, 11957.0, 93536.0)
('2021', 25976946.0, 67171483.0, 12007.0, 95013.0)
('2021', 25857579.0, 66946890.0, 11986.0, 97561.0)
('2021', 25708755.0, 66714591.0, 12400.0, 101003.0)
('2021', 25541644.0, 66430423.0, 12095.0, 104303.0)
('2021', 25384338.0, 66160756.0, 11972.0, 107444.0)
('2021', 25230353.0, 65916203.0, 9879.0, 108960.0)
('2021', 25083905.0, 65538753.0, 10963.0, 109938.0)
('2021', 24950451.0, 65321747.0, 10892.0, 110628.0)
('2021', 24806217.0, 65098300.0, 10864.0, 113609.0)
('2021', 24629099.0, 64823753.0, 11247.0, 116264.0)
('2021', 24438184.0, 64539361.0, 10907.0, 119949.0)
('2021', 24251909.0, 64271666.0, 10529.0, 122754.0)
('2021', 24062706.0, 63929216.0, 11503.0, 123910.0)
('2021', 23916080.0, 63599369.0, 11477.0, 123848.0)
('2021', 23765288.0, 63406544.0, 11404.0, 124387.0)
('2021', 23578070.0, 63128702.0, 11334.0, 126139.0)
('2021', 23359985.0, 62902360.0, 11948.0, 127235.0)
('2021', 23113531.0, 62491363.0, 12138.0, 128947.0)
('2021', 22887915.0, 62185469.0, 10942.0, 130391.0)
('2021', 22663424.0, 61947584.0, 9181.0, 131326.0)
('2021', 22445404.0, 61503591.0, 11039.0, 129793.0)
('2021', 22250149.0, 61292981.0, 10957.0, 129223.0)
('2021', 22021417.0, 61022599.0, 10850.0, 130781.0)
('2021', 21752049.0, 60732416.0, 11633.0, 131921.0)
('2021', 21456928.0, 60412132.0, 11612.0, 132370.0)
('2021', 21184885.0, 60165554.0, 10062.0, 132474.0)
('2021', 20934701.0, 59902466.0, 8008.0, 131195.0)
('2021', 20715626.0, 59422210.0, 9463.0, 128210.0)
('2021', 20536055.0, 59273596.0, 9407.0, 125562.0)
('2021', 20327598.0, 59058013.0, 9356.0, 123614.0)
('2021', 20047280.0, 58836221.0, 11506.0, 125047.0)

## Grouping covid metrics by year.

In [589]:
sql = '''
            SELECT substr(date,1,4) as APIDate,SUM(positive) as positivecases,
            SUM(negative) as negativecases,AVG(pending) as pendingcases,AVG(hospitalizedCurrently) as hospitalized
            FROM cleanedAPI AS cf 
            GROUP BY substr(date,1,4) 
                        
        '''

cursor.execute(sql)

# Fetching rows from the result table
result = cursor.fetchall()
for row in result:
    print(row)

('2020', 1711472650.0, 6828680724.0, 9640.38078291815, 52113.55516014235)
('2021', 1689066577.0, 4443463114.0, 11093.151515151516, 90629.54545454546)